# Generated by Django 2.2.19 on 2022-11-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20221121_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': (['-pub_date', '-pk'],)},
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group'),
        ),
    ]
