# Generated by Django 2.2.19 on 2022-11-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221124_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': (['-pub_date', '-pk'],)},
        ),
    ]
