# Generated by Django 2.2.19 on 2022-11-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221125_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': (['-pub_date'],)},
        ),
    ]
